### ISSUE TITLE
Breaking the bot with invalid first name 

### ISSUE THREAD

**Issue by Pistus** [scrimba/discord-bot#44]
The on-boarding stops working if you pass an invalid first name.

<img width="868" alt="Screenshot 2021-11-16 at 15 35 05" src="https://user-images.githubusercontent.com/1829960/142004999-dd663123-6f59-4e82-883f-e54e6e3e0190.png">

results in:

```
8|discord-bot  | 2021-11-16T14:34:36: TypeError: Cannot read properties of undefined (reading 'successMessage')
8|discord-bot  | 2021-11-16T14:34:36:     at b (/home/scrimba/apps/discord-onboarding-bot/dist/src/server.js:45:2775)
8|discord-bot  | 2021-11-16T14:34:36:     at runMicrotasks (<anonymous>)
8|discord-bot  | 2021-11-16T14:34:36:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
8|discord-bot  | 2021-11-16T14:34:36:     at async Client.ie (/home/scrimba/apps/discord-onboarding-bot/dist/src/server.js:45:3078)
```

**Comment by codeluggage** [comment]
Should be part of #47 with the optional chaining for the success message - closing for now until it shows up again.
