### ISSUE TITLE
Breaking the bot with a long nickname

### ISSUE THREAD

**Issue by Pistus** [scrimba/discord-bot#45]
Passing `Frode-testing-some-more-weird-first-names` gave me this:

```
8|discord-bot  | 2021-11-16T14:38:20: DiscordAPIError: Invalid Form Body
8|discord-bot  | 2021-11-16T14:38:20: nick: Must be 32 or fewer in length.
8|discord-bot  | 2021-11-16T14:38:20:     at RequestHandler.execute (/home/scrimba/apps/discord-onboarding-bot/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
8|discord-bot  | 2021-11-16T14:38:20:     at runMicrotasks (<anonymous>)
8|discord-bot  | 2021-11-16T14:38:20:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
8|discord-bot  | 2021-11-16T14:38:20:     at async RequestHandler.push (/home/scrimba/apps/discord-onboarding-bot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
8|discord-bot  | 2021-11-16T14:38:20:     at async GuildMemberManager.edit (/home/scrimba/apps/discord-onboarding-bot/node_modules/discord.js/src/managers/GuildMemberManager.js:260:15)
8|discord-bot  | 2021-11-16T14:38:20:     at async Object.process (/home/scrimba/apps/discord-onboarding-bot/dist/src/server.js:5:1926)
8|discord-bot  | 2021-11-16T14:38:20:     at async b (/home/scrimba/apps/discord-onboarding-bot/dist/src/server.js:45:2708)
8|discord-bot  | 2021-11-16T14:38:20:     at async Client.ie (/home/scrimba/apps/discord-onboarding-bot/dist/src/server.js:45:3078) {
8|discord-bot  | 2021-11-16T14:38:20:   method: 'patch',
8|discord-bot  | 2021-11-16T14:38:20:   path: '/guilds/684009642984341525/members/910164173420384256',
8|discord-bot  | 2021-11-16T14:38:20:   code: 50035,
8|discord-bot  | 2021-11-16T14:38:20:   httpStatus: 400,
8|discord-bot  | 2021-11-16T14:38:20:   requestData: {
8|discord-bot  | 2021-11-16T14:38:20:     json: { nick: 'Frode-testing-some-more-weird-first-names' },
8|discord-bot  | 2021-11-16T14:38:20:     files: []
8|discord-bot  | 2021-11-16T14:38:20:   }
8|discord-bot  | 2021-11-16T14:38:20: }
```

**Comment by codeluggage** [comment]
Needs a guard on this line: https://github.com/scrimba/discord-bot/blob/main/src/onboarding.imba#L32
